name: Deploy to Github Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.10

      - name: Install Wasm
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.PICHESS24_KEY }}
          
        
      - name: Build pichess24
        run: |
          cd ..
          git clone git@github.com:eguneys/pichess24.git
          cd pichess24
          wasm-pack build --target bundler

      - name: Build Shess

        run: |
          cd ..
          git clone git@github.com:eguneys/shess.git
          cd shess
          pnpm install
          pnpm build


      - name: Build
        run: |
          pnpm install
          pnpm link ../pichess24/pkg
          pnpm link ../shess
          pnpm build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist